FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
EXPOSE 5000
CMD ["npm", "start"]docker push 462972379716.dkr.ecr.us-west-2.amazonaws.com/auto_showroom_backend:latest